apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homepage
    background:
      image: https://cdna.artstation.com/p/assets/images/images/039/686/702/4k/pablo-dominguez-lgr-shapestudies-v003-pd.jpg?1626641885
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100
    theme: dark
    color: slate
    useEqualHeights: true
    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Observability:
        header: true
        style: row
        columns: 4
      DNS:
        header: true
        style: row
        columns: 4
      Network:
        header: true
        style: row
        columns: 4
      Home Automation:
        header: true
        style: row
        columns: 4
      Other:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            description: pve1
            widget:
              type: proxmox
              url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
              username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
              node: pve-01
    - Observability:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.local.erwinkersten.com
            description: Grafana
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.local.erwinkersten.com
            description: Prometheus
        - alertmanager:
            icon: alertmanager.svg
            href: https://alertmanager.local.erwinkersten.com
            description: Alertmanager
        - hubble:
            icon: hubble.svg
            href: https://hubble.local.erwinkersten.com
            description: Hubble
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""