apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homepage
    background:
      image: https://images.wallpaperscraft.com/image/single/night_starry_sky_trees_1334550_5049x2840.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100
    theme: dark
    color: slate
    useEqualHeights: true
    layout:
      Hypervisor:
        header: true
        style: row
        columns: 1
      Observability:
        header: true
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Hypervisor:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            description: pve-01
            widget:
              type: proxmox
              url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
              username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
    - Observability:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.local.erwinkersten.com
            description: Grafana
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.local.erwinkersten.com
            description: Prometheus
        - alertmanager:
            icon: alertmanager.svg
            href: https://alertmanager.local.erwinkersten.com
            description: Alertmanager
        - hubble:
            icon: cilium.svg
            href: https://hubble.local.erwinkersten.com
            description: Hubble
  widgets.yaml: |
    - search:
      provider: duckduckgo
      focus: true # Optional, will set focus to the search bar on page load
      showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
      target: _blank # One of _self, _blank, _parent or _top
    - datetime:
        text_size: xl
        # 4 januari 2023 om 13:51:25 PST
        locale: nl
        format:
          dateStyle: long
          timeStyle: long
  docker.yaml: ""