---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_PROXMOX_API_KEY: AgBARAuCeCr6XSa5D106NOF75+TeaLjrl4SsvGLuXimiM51Db9/iSJgPAvWvrlPfZbVfKBltMF7DlJBaEQM4Dut+B0uEg+ws2m21OBgZDvVMOSby6qPioGdpbSW/P/ILzzlprliv2ErU9iyOTMM682hhBIYTEjPiqk+p9eYJ3a/lopYNRBvhrzI1jjVpQYhfjcFMuYSfLzeo/KhaOTOEhQTjvoVpxXb926Wfwr+8ECu012umBysxpZnwu+W60KxL1O1QQQwNeMzRkB059UHPSq6SAX66KdCl/Eo6c6WZKc3ka/s7/C6nTGEYcukOJWCNfGgSF7YcqKn0wkXdZsdT+Loyu1VS/RJchII5mj0Zk8/2sClk6I/9EjSyEqZOk5w8T2zhNGC07ktu/wVql0qGThEsNZwqvjHeu7mxX174RHWYI5bM+BBzEH4YUhZUK5itRhiD/PGcG6+fxtNXUAHEKYap9arWPbcmPHHkfZ3Y6Xr1VlFfgvNliEjvIOsS1mmGMTDtUBg6pUiA9oIE2X+loobG8jgcyKMBXFePxw9nk1uuVTlPfrNmA+EfFpyaHjbJDV5ZrAYLDERrblo5QkDQuOcnTOFZOlPtFgsn8d1FhXIr78+nx5RkcAgQKVGfufcMjyVcKzu4w5wpIZXk2tCS4c6Boi7ApdFwUu8H1nclIPhBJGPi5nfC2u92mJJ4/K5gbY1S85qL1Bg5BhQi
    HOMEPAGE_VAR_PROXMOX_URL: AgALnEWEo+OUAbvXPAqaAylCYKaNdhVvH24LcJCQyMwzMTlwqwZYEajUf1jCRkp6OxQSnouE1t6mcdGc8jp1h4cxzIEWwwR8LlxUJcGhhdh5GyWSW1Pqcqf3o9Lsv5vFW9SbLbTYFky5mSJre3PgnXdYy7hyVZjCN1yXHQDLlBFd6H5JqzoPAFHmLgxcAmhDqDF/jGpnW2hTBIDa0oHnAPMc44mXDgUcFL9PG6g/buRPaQV+HPzVStoddf6Y6hDoa95MRSuX5HqghcBRnDs3k0kTKSx84/SgxXQlB/Luj8YT6ASuBUMweYw1AmH5300tKUj4acyKp0S+6kfN68G+gsVmyuJJgz+yaC7B46HrcVchD950oPrEsWkFtl/Qs1lR94OdY9INLaO0Xi7H4J/eN0RvOdJLMbCS0zCRuNWxRNQLvq+PB1pEDiH+UbaJ73PqIOVmI3fe4OjbSBKWa/UIByiaF0mGHhvKZM7mn3g1KQVc0dBlDC0ITQhCMz3TVKG1gl1aa3cGvqUWuM2CDHqURxVwLyfMrtIwAdytOIRfVo3IfqERPYRXReDvDn3I0ucoxaqUnaRVLzs1vb7WIVRFoH67To3mc12c71ELGk2MFdEg9bheCEzq6zdt0el8RLDQZrrLONpGyPaKppSzoj+bub9Ms9/QNYPCVsZu+nLe84O22lQmAUa1CwaYG3W/jr3FiJuYUM+Z6TRCyCN+zDAAriZM+x0TXMWFAyn62FXLOHMGkNI2QbtZ4G8/mEM=
    HOMEPAGE_VAR_PROXMOX_USER: AgBosAoRJK34ZFnUDtn4yE5SzZL8wSYY3SsuULLnU7QyBWFV5f0H7hYg1DlpRm0M/ooVKxX7umptop2NZn+yx7WPxaRKJPTu7/HF/J4RoMKaqtByvFTOX7vSJEocTg9kIGw4bJtnyLAHP/jt5A7FBr3aVZaFJ0dSrfvamkU6pFnz8FLVl1zfzt3268v9TquKrgYKUIKaQ8yalUBHhkCPwkedqPUkzGOcliUiBYeCAxUA7xqhKXqmyj+o3aHiO+6pId8RhrHfxL+LChzM0ZLXlJYBdC+eMylt5kgvVHNw3L3HT6MxBDm0P91DJTF6Jh6M8ChmOpNzjXhCrbc+mRA5Ddfjuyo3EWCu6ynTQLI3dACpzeMiJfm2u3swzxYnj3FJYEuXhN+hQB6o2E3lLiTWhjqBTltgaEckiVGKM+JK3+PmdiTbK8Kstn5dy8+Ay47i16w8g9HFv8L5O+EbFvHhcCP1UEgL/ThHj3G52efG0ozEyitBlEraGmq2LqMVaVnEWvypQcS1/9yfsBWG5x9HAs+sUc9svlh15VXz8KGKdW4/joNL3b7C+jY131KiWlAPxA1IJkvjo99HVtAqeAmwynWOwCZY6PRmZWhHFOSLFQVbUw93GzD6Z1thWClGfMixn+fvjxnxAgvTjJ6B/DojeBka0TRkDYsRMJBmIDpdBHG6K0i4Ud60u+UrfhP4VCXPtlOK54R7zXCnxg==
  template:
    metadata:
      annotations:
        kubernetes.io/service-account.name: homepage
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: homepage
      name: homepage
      namespace: homepage
    type: kubernetes.io/service-account-token
