apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homepage
    headerStyle: clean
    language: en
    hideErrors: false # true, false
    background:
      image: https://images.wallpaperscraft.com/image/single/night_starry_sky_trees_1334550_5049x2840.jpg
      # blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      # saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      # brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      # opacity: 100 # 0-100
    theme: dark
    color: slate
    useEqualHeights: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google
    layout:
      Status:
        header: true
        style: row
        columns: 2
      Services:
        header: true
        style: row
        columns: 2
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Services: 
        - Grafana:
           - href: "{{HOMEPAGE_VAR_GRAFANA_URL}}"
             icon: grafana.svg
        - Prometheus:
            - href: "{{HOMEPAGE_VAR_PROMETHEUS_URL}}"
              icon: prometheus.svg
        - Alertmanager:
            - href: "{{HOMEPAGE_VAR_ALERTMANAGER_URL}}"
              icon: alertmanager.svg
        - Hubble:
            - href: "{{HOMEPAGE_VAR_HUBBLE_URL}}"
              icon: cilium.svg
  services.yaml: |
    - Status:
        - Proxmox:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            description: pve-01
            widget:
              type: proxmox
              url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
              username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
        - Proxmox Backup Server:
            icon: proxmox.svg
            href: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_URL}}"
            description: pbs-01
            widget:
              type: proxmoxbackupserver
              url: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_URL}}"
              username: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_USER}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_API_KEY}}"
        - ArgoCD:
            icon: https://icon.icepanel.io/Technology/png-512/Argo-CD.png
            href: "{{HOMEPAGE_VAR_ARGOCD_URL}}"	
            description: ArgoCD
            widget:
              type: argocd
              url: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
              key: "{{HOMEPAGE_VAR_ARGOCD_API_KEY}}"
        - QNAP:
            icon: qnap.svg
            href: "{{HOMEPAGE_VAR_QNAP_URL}}"
            description: NAS1
            widget:
              type: qnap
              url: "{{HOMEPAGE_VAR_QNAP_URL}}"
              username: "{{HOMEPAGE_VAR_QNAP_USER}}"
              password: "{{HOMEPAGE_VAR_QNAP_PASSWORD}}"
       
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: sm
        # 4 januari 2023 om 13:51:25 PST
        locale: nl
        format:
          dateStyle: long
          timeStyle: long

  docker.yaml: ""