---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_PROXMOX_API_key: AgA3HghyAkiA+GvYCx+0CZRUZ+cwIXCb5BWR4y+Yvr0fJVuufUJcAJFHvUIut4DXQRE39Kpxd2tKf89eL2YMgFHVcRtQq6QeU4Lk1joya8Ut6kjWHS0Ivo4lULMHck16kqHCkNNr+Fox4qG70dnXymneBEjRjupPSEKFoM36QkV8jf42zDTaqGj+EUSp/c3bfk0G7yI9bo7RtMTr0unnb6K/lZu//FAeL2w5x++UtJtcbK5+HBt+3GY4Hnsk/OiMctGRLp/e5jxPDANvJW/Pal+brZT4W2Hgws9x/P1KwngmrhHzTzTI6h1jzCq/ZckyZVg3cGaTh2hLPdHQ9X776/lHl234P58VzcU7aKUvY66LU+uu14zRAZvMikfT4azmOFWtzSfSshatBfDVQsfESRLfrpNRgGaDEhKhkGXDzRRBJyReW3R9X0sirL4BF96JU8p/SkU3b144IsugaYyUL/7Nt5pp2RUAwAR/xYbaxhPQfS3zqqBpYAkerNpc0vdLK7imuDyhFZIhItERVPEhSyobpn3HPa1mvdCQsbJCpiFauaKho12x4ngczS3oQFZnfPkqlUyZlL3YO4LJci8oy4svfmQaUYAKizgoAOPlqh74/flBb+wTc+oaCniJHabIlydvCxm3UGejLGfm89UqDYgmuUdOAm7ZW4jqElqTyKkm3MOk3RcJIaL20NjZumZKxxHiWiUi9LmDNCUL
    HOMEPAGE_VAR_PROXMOX_USER: AgBm+0a+ATtMmZFqr623+EWnE6j3lN/FGAg7TybL8D8yDnoJp8KPBTm/GCv7nSTIsp02c95wScwW3GBwTpYAb2WSnVAtApnajCNdi/PwACFuh9Qp2o769rNhpSgVYtU94JYaWHkdFSgRsSSXqgVtxAuaFCIGOn12pqdZDHQkrIzmH3RV1ZuIM8jDiiFw81pJVEOP+r4alQiZWviFeUYHKJ0ykRk2cJAoL7aIDnaKbXCGfSNBa9hgDmjEZtbdkm0bQxvVL9Y3giyWVdTu7sxDxqP0TLMAAxxlT0ZUP9COXRQ8LcbbMzIZXDgXyx/tmDBTja7QmwLH1kmmU6KQGvtNEHAOYIy1cGCHfSlExy+K84X331tbD2ivwAqZ6rnSI2eRse/40yKZniXRJlBbo8krqI5K0nyhlxKpAE0/IXiFA2KwaDNsPUjY3Yz7mKr7Toxkuq8ch1KLQe2vOK9A79sFUKKnxs0IvARe2FxTHleXm3+lvlLgRk2KD8kG8l7RDidi9QbkVHVQy28ZxcqKCNAhMVL3Y6FoSHvYEIb2rNsizs1YFHXB45oeg7K4dB8tl56QpHwJbSvNjxv11gGjTy43JOWiipqXbHah/cCwek7spTCIGLwwn4/3zUTSajuw9unThA9nbQ3zJ8JwmYhKE58/5CT8cQ5b4v8un/kLkcCKf4etrZsnDniE2VrormaiwV3bHs6a42PyoxH10A==
    HOMEPAGE_VAR_PROXMOX_url: AgApPM/ImcWrQqTjgYtJYmwV7NGq0fU6BzN5aIZq2iHc0gDIvvPOWZQKeW1tp/rCY9jptA/lrjiF4T9d1j/MXeyrA6Mg3500eAAkOR5SesJt6r+T0i6z0eUEKE42dMvD0eIsBWA6qkl2YRZx1jSi0USG4dKzTZq6RX1Bznn7USIJvnsdrSmbi/SWR6ad58nYnd22Nf9o92g3yy6GEuRqWUMPiQhn0Tj94yza41ieTL8AVEGkRBJYFID1E0OexirF4yBLepSiFQXyfUa/fT5OescUVrCPvITyIPaDcL5qjMRiMV6nvoUBQ7Mk2yNJ8ytfXleasNoAUrGzRmZgFtgbfvupPFgbBj/ewIHr8eMXm+ZFPupVVKFmN7bbawVzau/KAkNGbIO6k7B8Z9qCe5ReC5EZK99inaVaMCPeAPSwl2waGv+6XBNDd/xe9fI1zK9QciycIMe2raO4dvSSJwvw1tKXVUgCr0rw9NcGUYsW2m2rIOqtXPuxw22XeQ2fd2XG1U/vgTkH2e7mIUcBl/K87l08AhUO1kkxXuGO/4qc76sVyp6KBxNGnXuH1EqR1L2hy3+bWgaaaXtETkV0YBUpeC0IByh4O2iX8sGarPdJNba9ofdMW2hYCGCcOdMhc7xVDcaDLRz06LWJBiOGpYZ8OoCug8O5omS489CaC0YuqEHr2BEDd8/fqt+27XxqhBLmBJ5o9za5gMMCKXuCwjlAo5p0ItvbOcUJgEwDkCgs2HsBcx29zhksHbp9Utk=
  template:
    metadata:
      annotations:
        kubernetes.io/service-account.name: homepage
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: homepage
      name: homepage
      namespace: homepage
    type: kubernetes.io/service-account-token
