apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-local-erwinkersten-com
  namespace: gateway
spec:
  dnsNames:
    - "*.local.erwinkersten.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: wildcard-cert-local-erwinkersten-com
  usages:
    - digital signature
    - key encipherment