apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policy-management
  namespace: argocd
  labels:
    local.erwinkersten.com: policy-management
spec:
  generators:
    - git:
        repoURL: https://github.com/erwinkersten/homelab
        revision: HEAD
        directories:
          - path: kubernetes/infra/policy-management/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        local.erwinkersten.com: policy-management
    spec:
      project: policy-management
      source:
        repoURL: https://github.com/erwinkersten/homelab
        targetRevision: HEAD
        path: '{{ path }}'
        plugin:
          name: kustomize-build-with-helm
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - Replace=true # https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users