apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ciliumL2AnnouncementPolicy.yaml
  - ciliumLoadBalancerIPPool.yaml
  - hubble-http-route.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.16.5 # renovate: github-releases=cilium/cilium
    releaseName: "cilium"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
