apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

resources:
  - ns.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.3.4 # renovate
    releaseName: kyverno
    namespace: kyverno
    valuesFile: kyverno-values.yaml