# Deploy Node CSI driver only on worker nodes
node:
  nodeSelector:
    topology.kubernetes.io/role: worker
  tolerations:
    - operator: Exists

# Deploy CSI controller only on control-plane nodes
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
- name: premium-nvme
  storage: nvme # Storage name at proxmox
  reclaimPolicy: Delete
  fstype: xfs
- name: standard-ssd
  storage: ssd # Storage name at proxmox
  reclaimPolicy: Delete
  fstype: xfs
- name: cold-hdd
  storage: data # Storage name at proxmox
  reclaimPolicy: Delete
  fstype: xfs
