externalHostname: "kcp.local.erwinkersten.com"

etcd:
  storageClassName: "premium-nvme"
  monitoring:
    serviceMonitor:
      enabled: true

certificates:
  dnsNames:
    - kcp
    - kcp.local.erwinkersten.com

kcpFrontProxy:
  gateway:
    enabled: false
    className: "cilium"
  certificaateIssuer:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  service:
    annotations: {}
    type: LoadBalancer
  monitoring:
    serviceMonitor:
      enabled: true

letsEncrypt:
  enabled: true
  production:
    enabled: true
    email: erwin.kersten@gmail.com

kcp:
  tokenAuth:
    enabled: true
  hostAliases:
    enabled: true
    values:
      - ip: "192.168.80.202"
        hostnames:
          - "kcp.local.erwinkersten.com"
  monitoring:
    serviceMonitor:
      enabled: true