---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBuZg9sPPhIjqoY3lfErYT81YaLwXTykz0ktqW437ZrVdkCcSLTNXHRDMk7UPFr86+bhhnH1QHhR/ULg9JkX68I232v2/dR4mn2FLX4T9WCf1H+QPZ4PNJOmKrmxgWvUfLx/rzFnuWSQQC0dxobnhWm6AstVZCDvYAsRoQe2RUKN53IIt3bsrTVTiGh4RZe3EavemtIdV6r8Uk7oDueBR/XlQNLqXmITUY1JIcFsmZpPmk4mvXZso4BmhZkWmInZcZCS1fLW/65oDVOgwxsHqN7OIcaZ1z2DwVKccFqgEXBk9qmWi9Vzix4FLAJKN4Xxd8NDS0jjH7iurSGn2TXiBRp9RDFcXhbwqfbShaNmX0a3PSsLa/JTTYQ0PutzcgXlKcVAZtFvJPqwy2ZBU2q+P0JQdBGgeT1jHVl8THSXSgr4kLkR0GJgythOmpowLwoVet9Yup4JTnxlaVEoL65eVzsuBS+j8VXPY+ze1h083cm7zVoFVjO8ubOq4uXi5fsW10HDC5vEUy0IC2RfLWcUHZ1DL5pUcrxJmuZ5y6uKJm8NQcaXWXqv8WPT60O0SCg3GEZ3Eguaqm3zP3BCnqHKamBbYb6134d1kO8waweZ2Eg18Qq+VpIe6YCYd8hVgs76Zt5tb92s05hv3THR8xKdvVQAstxxWO0OqqDQXrG6U/7Xdbacxvz3KHRl/B61WMew4A92A6GkTWelkFG
    admin-user: AgBifnksvE6X7rKT8CQDZaYlEE8bcOd7YRdDn53fIahuDEW63Oqltuux5U2CTriROKqEy/JQzUA46mxq5MkXLbtFCqeJwgXqlEVqXpBRGHCSCqZZnRl5aYswKxDg73Bi3qo5CcqiLFILmLbwphm5BOY6b6ZCDeDCyCDTudyEU1wDYu2wPVz5kXq+mg6vmR8P3j/6oeQzMTv3Hctnq9gVZLvsNdJ3mxoLmaZldUjWIITAf8YDlC1f6w5hOT0kYUfrLoZh8XHS2AUFP52wPjMgnB7iKlcXvaxW3bIlsbZPLQmvqh5lM52s9PnYmINvfiqc3kMQJQTtzsIy7NYw0OmVaXXcPUr0X1/9viHQ8nzy3sC9Ho2oRgaGTZpgbbk4JYtYH0lBpbMKdCQ3uTv1z9qGvQRy5ShD34pJUsF13lu+cEWAaew3w6hI8OzOa/YSiZpth7qILab8Bb5hXhFg6ORTQIQuSWMoubzx59TTWCHIQnTe3q0il/YEiGuJexYR7gkERAmgSKjCv/6JSYySMGi0Bb74b9HB9CQMgKvDELemQlAr41uQf/wf5sIjeeCpUl1QtghSNhocVcomq/dQey2l5Sau+e0entOTuYYamPs5K3IdqRnH0HlMAUvmkDorv15PQ2F6qRUvtlmRgQozkzM2WgfNtco/swiONCnybWbSVwG1noL0l3Iv4bBDnqpjV+YZm37wfgmWAA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-prometheus-stack
      name: grafana-admin-secret
      namespace: observability
