---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgB/5RhMKbg4EJEgIrEpPRuzGq4LzT56jUskrW3sR9BwheAaUbdHfnXn5XUZ4sz4cJORBFFYmmxS+CieXeUsMvOy0dOYIH+EvAxpNlHH8rqVcHzkMj5VIsZmQh7X3bE+9GpImq8d+/fxQTwspYQN5p6c7wxD4NcDncNqO7h1q49944DfsI1TXH2gm8fhdYiTXGEJrEc1JJYgDfzfd0pZmUMTdZJq8EeyDJjlkduVzOm1CHd8JbN5JPDvNPd2l+YIAz90kOFCzgEOkEjW+VUm/aeck31eO3/isnZXzB6g4jgYnNirOKgD1wlcl/58pDuukq0E7AmLj9Om0TIgM3yYgcIlu0OlnyEqFnkhqCEGXFLUhx9UT6nZuo+KMrD2ke/shjpoGRLN0RGwylg9rBCa8xJmRhSihVtFhpCc7ZHM4G/9OLi/xRR3/9Uh35Z/ur1QyMLx89XJoHQC+Dl4l15khDqxOCjOQmt22/fJrB2MNDISjtsVozai7BamsCxCb1Ohz3PJoqU3rf3mfjuqSAYg/DG1cmyA4jrbdk683J6G18lmm7UfLxEJAsANdM4CXJ9lRjVbJoSOF5raslY+XBFUtkF8Riz1OUu7hmoxmLPhOfJwxqQYpfW5PI+PqjU4jZWrRORnvX0SJWw9Xu3zpD8Ov9K2RJnpFQ4YokSQ5eQVoXa71qNpNozY52M2km0dAZbGhnFNPNpjtLxGB451
    admin-user: AgB2o4cKcYC+NSmsrC+7rUPQdRfeGpxS93xO6yXaI/WJu9LUzH7TOAIIi97PmVQDXzlxZY8rumPpeuz4IUK65tfWQ/ivWAvPUOEnBJv5dNUPH1HqD44/RuMYIgC+F+nGapEJNpmaFr/Cj4tduUR+LkE7m2rb+7ryJud6pBiJ8unvR1Vfj2ISS+vKXvPGiH210ZbScLGteVgNGA8N0oGY2SPdnznvLq3+1FPhmopkyhc41OB3gYN05EZA0P85wGS6FWwZSiIq2mmV+aKr235UNTG/67HxaW/LdXTAxZ1wEI734WstMr3oJxNJBPxNeY3LF5hpWb/5rK4is+7KBECuAzDz9vVa6fVeNzD9RuH1OM6M0EuSLMKPmzOjuv9YRKea22BrqAkhMJMfbRXgi9jIMqly6ruRwtY8HcqiWZ/ImWrM6w00rcK3DxXzrxOmKrFtSOsubQi/eGgztHPWWPI2PyVhF+D3/5MmPc/IUsHGvbYE0BXR5KYC3XsgxWsNQC/FmqYJASxn8cM5a0sHb63wnBWcO4hQP41ObtWN7NpKLjkFUIeCdxn/dmSxH4huHmKfcwXU2xKFLZjzjMNSHEHZnBGsSXM20p5FzmOargAnaRacEfh7sZtGQ4cWJS0F7QHewFc+Ae2s7QdZYxMjukNABDQ5IOKWUGnOAJt7ln9uJ/gemza5j8Fg9Cf8adlkvR3Ve/uC7aE53g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-prometheus-stack
      name: grafana-admin-secret
      namespace: observability
