---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgADu0jfx8UExdFMFbcEuL+n83145A95YuS4nHAOOCJtmH2jiymLaf5BGifFYrZxPvvR4G7H95JZ11Ps7P2c43trHYnLy95CVafEgV/XIQTmkB8p2egYXxW/jzccO50HvUdQ5fuaJZCBq5Vnw9mwX4YEoEBrGJK86GhT9d6PmRWEGFTsb6Gu8Ph4L8plqm37AKANWB5ErPaP2HTVSjJ+Y7tB+eYSC0MYt1qcCWM4mJNJNaSv17EZ4s6CBORFa1J9VWBB7es/7mW4GafRLaPDk7Yl8U/rX8t1EDUAXV7RwbTpBuJT806d/DFCO+YoC4XtlQdOjyL1d6LryxiCOKfWopAPpi7sn1V97D7IhjB1QrKGdYTbBg29N6ok2pZVkUfP2Li/uQJVm+Z/3ZryUfyTLpLhdbVz/sateeSte4AzDenASbTPsO61bozuOB5JQ6RhFydTgjHbsU0dlMEsp4JntpD0wQMsrooMQ+V+XQLtBmCMvnDiztfLgTKx60LsZyEoE3OKraV1FUfCaFORwn3Q3FqPiY2mBGAOxuFrUk2Gra05szmsiFYLZZC0t7PnaUyDcYenP6RRreOkySERkD3WjgsKK9VH7epLG3CmDvKTcJjwP+rQF6YDP9nGQHr6G8ns925Z1H+ZPWD6bBhTdNyYEBJ/MZLYw3z5gjm9OHnxx3qjsPAKKSRrbqW4PWAzlUekPi+SddLD7Fn/q7DUJNNH
    admin-user: AgCGSbYzVaWcW7zVC8Ud8xAPE9eNhZd2qeSUxy+selgdEc7W5ozLbPwpjasU5SZIvSf7Su5u0kgLDJUUF0rbjPflRxzDBRfImmo757jYVo/WiY92wy6THo6IxVygejvURdbfT1g4MUDNg1y5osQyFvXN2zabWBm0pbmiseLoViCcG/7WoKPsFMZ2W261fkV5p767mCNehMW8O1glaObeT2rY629ezlhWjflxy4SXYivoI9Xw4/Ox8UZU5iCUvxFI75AVJw821eO2FzntepkRwmEkHBUxPAeHcqEMXBAwgzhBaQDbPyANws4ZqF8qBRSWLLOzRKNOeLX3vvrqwd+HxY5yMvjkvfNBGpP0oL+Y1vm3i5hb8eBVsX3YsNGYmVE2MRZ4Tj0oLqQ1zmMQhaSOMIY/Bm6lb3eGQpj6uaaJUwwLlPF3RrwywItTg0wwlZmYsXR9vnPlpOM2YLa+kEUpAOjPt54lbl4Oh/BOhWZce8IZQUVEXVqZ3z1JsAr7x9/oOO4xhxd4wQ9qwsOBmo8vPkn2Dulid/1aqT274Dke9qXonW0kMnCeOaK7MHgI4YkXk6qB4D5LlY4i5MLxTfErYYf38OUbRBKBeSDCk3/zvMkWnjGJ4gYn5jKutjVlwWO64NCYbVfVjk0LL9I4RQGx37s95bXOHTODxE/SOhEXjHNmiR2+92wCLmL+3og6XWAJ8s0GObEe1g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-prometheus-stack
      name: grafana-admin-secret
      namespace: observability
