apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - observability-ns.yaml
  - alertmanager-http-route.yaml
  - grafana-http-route.yaml
  - prometheus-http-route.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 69.2.2 # renovate: docker=ghcr.io/prometheus-community/charts/kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values.yaml