prometheus:
  prometheusSpec:
    nodeSelector:
      topology.kubernetes.io/zone: pve-01
    selector:
      matchLabels:
        app: prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: premium-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi

nodeExporter:
  enabled: false
