
## Install Prometheus Operator CRDs
crds:
  enabled: true
  ## The CRD upgrade job mitigates the limitation of helm not being able to upgrade CRDs.
  ## The job will apply the CRDs to the cluster before the operator is deployed, using helm hooks.
  ## It deploy a corresponding clusterrole, clusterrolebinding and serviceaccount to apply the CRDs.
  ## This feature is in preview, off by default and may change in the future.
  upgradeJob:
    enabled: true
    forceConflicts: false

grafana:
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password

prometheus:
  prometheusSpec:
    nodeSelector:
      topology.kubernetes.io/zone: pve-01
    selector:
      matchLabels:
        app: prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: premium-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi

nodeExporter:
  enabled: false
