---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1NO9OUf34P+E6hCJVTykgs/iegJxGGwY9W/eIAH+8kdYmVj71BnwVLpbt7V5LeqZIlGqwQCLrzwhNMAXQRsApTvYrGcK9ZLKKnAeXDAIKREol46YKYNLotPnZWaufm/eDPGhElSRuyGMuTCFqV4rw8kXRDazQR5sE+DtVpdcTXggJUghd+VwBAlRaFqF70Xw9A1iDqLObGWvwN0btV02ywMxwIvIEiZBYtKVZM717bc0SML4CDTmljcimqSLkhRaAdNtKqm1vP+LwyAZX1Kc7EKU4iMCBTPI3Fl1zQ7g61kQyyEqdw5do7UjWAbZ8mBrHLx3m2JHdUmzyCTmbjPAHCkEEW5t9C1QKUEq0gxe+kBDjILwhzyYkMh8b7tbbNVYeZdNTdOKB4WOWfI2/y4ezjZXcaQly+66UiWOpbzq+Tto0axTf2PyqkU4BIw8sPWtrU+D3f8pInxH2rEgcNboOqIk5N2cEtpGuywlt7hLG7vAQUmvnsfsAelMrE7YMD1DvPNZBENVinYjv3RBj1YTBVuYDGoaiP/XUduggKIHs3Syl0qxVB5r0wl7ZSF6n9tk4Gi2Femm/Oxw8aXxvU051OdRrfVBRgg17hHvR7o9Qjk6xjs5VjAVlO8pE3eL65+CCMxX3MO8sWWnCmaCXHzJMuVFJgHqf6BmeYau0EYnb2ZZQwpq5DmsirQ33dap3knSmm6N2NVQwrLTc7n8jwcP2RyojnPOtZl2+c4l4CGTue8+xMLrQYEANYrsoOwbqrvPDFNQEYg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
