---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAa0TJWwTMdNgHeNfHsAbcJ/lCvelQYY0r/bASMCWVu8JBOyJG+9JwKFwt6kMrF0NDPywvtyezTn4L6n8IBURZ/vEOJk4H0VoJwCiTj93G8e1zABUr3zePoJHJ9vPL+6ORxR6kY6H+R0CB+ImWwANIxFqUBLEwDv/sNKlRZttJN3QAgGdEjJjNVEFp1PEErPPNpbzWgB2O5gjGhcmmUGgqrJv0JlK0cA5Owen93fcN5j6TE2R55HMUwGwbvVp1f7lbQQ93QnDkLXoWz5JQQshD2Uhq+HvoPWnjvpn5JPnrQCHqkzIaUN2OWbv1q9xMKfMb3T3RpnoQaJFWP9Av5x5dZBxlDtCx8eGYAJGcomWOpNO3pxCaHbMb8WixwjRqd9MVpZUS5bY/J3TX4Q3MLLGzUdT44Amns6cy12dBwYIPsjGHd9+TFMO/i7HrMulsJV+zer8h+ZdNWxiaYUVimV+FSJpMj3oz1hBcqU8xDstiobTuQaSuNjhzizs7oIMFov1umjet208Y9GkoT6dbn2/QbijjpGFsb4rya7ybIg8XBYhySByKDpWn0/dHDZS3IpwXSZa3tFotSj1yfjtEwjDBX7HgnWkTmaCo11yMs1r9UU+GYN+eWfQ5hx48Yg/VthjTS40jCcfmdJDwZIu2RGzH+vN2q9H5oW18VqWYFTRQFsp2/hyFRcTUZwl6JrA7H+VHlXmIKKZMizA6ac3LC802UUcam9IK+XiD7dgTgRiSxdKJyJXgoNzNbNIMrrgGBqe+fTPLNsQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
