apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: erwin.kersten@gmail.com
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: erwin.kersten@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token