apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm-namespace.yaml
  - cm-cluster-issuer.yaml
  - cloudflare-api-token-sealed.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.1 # renovate: github-releases=cert-manager/cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml