apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
  labels:
    local.erwinkersten.com: apps
spec:
  generators:
    - git:
        repoURL: https://github.com/erwinkersten/homelab
        revision: HEAD
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        local.erwinkersten.com: apps
    spec:
      project: apps
      source:
        repoURL: https://github.com/erwinkersten/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
      syncOptions:
      - ApplyOutOfSyncOnly=true
      syncWave: "0"  # set annotation argocd.argoproj.io/sync-wave to "1" for resources that need to be applied after the first wave (deployment.yaml in this case)
