apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applciations
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/erwinkersten/homelab'
  destinations:
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'argocd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
