apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec: 
  project: app-of-apps
  source: 
    repoURL: https://github.com/erwinkersten/homelab
    targetRevision: HEAD
    path: kubernetes/apps
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true